export const GUEST_UID = 'Pyino4SsfsPXgD8kNYyKBIO3pMd2'

export const PRIMARY_COLOR = '#FF6347'
export const SECONDARY_COLOR = '#f5c4bc'
export const DARK_PRIMARY_COLOR = '#f74727'
export const GREY = '#7E7E7E'
export const LIGHT_GREY = '#D3D3D3'
export const GOLD = '#F9A602'
export const RED = '#FF0000'
export const BLACK = '#000'
export const WHITE = '#FFF'
export const OFF_WHITE = '#F5F5F5'
export const PROFILE_COLOR = '#fdfd96'
export const PROFILE_DOCK_COLOR = '#fcbf49'
export const LIGHT_PINK = '#fad9d9'
export const GREY_BORDER = '#d3d3d360'
export const GREEN = '#00cc00'